apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: leader-testnet-geth
  name: leader-testnet-geth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
status: {}
